### ISSUE TITLE
Update to support latest version of apexcharts

### ISSUE THREAD

**Issue by nesha14586** [apexcharts/ng-apexcharts#365]
When I run npm install I get this error:
```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: ng-apexcharts@1.12.0
npm error Found: apexcharts@4.0.0
npm error node_modules/apexcharts
npm error   apexcharts@"^4.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer apexcharts@"^3.53.0" from ng-apexcharts@1.12.0
npm error node_modules/ng-apexcharts
npm error   ng-apexcharts@"^1.12.0" from the root project
npm error
npm error Conflicting peer dependency: apexcharts@3.54.1
npm error node_modules/apexcharts
npm error   peer apexcharts@"^3.53.0" from ng-apexcharts@1.12.0
npm error   node_modules/ng-apexcharts
npm error     ng-apexcharts@"^1.12.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

It seems that `ng-apexcharts@1.12.0` requires a version of apexcharts within the range of ^3.53.0, but I have the latest `apexcharts@4.0.0` installed.

Can we get an update to support the latest apexcharts since it's a direct dependecy?

**Comment by junedchhipa** [comment]
release ng-apexcharts@1.13.0 which should fix the issue.
Please report here if it didn't, I will re-open

**Comment by teukusem** [comment]
@junedchhipa i still have the same error when build in react
![image](https://github.com/user-attachments/assets/d6017ed4-172e-4e4b-a396-38df39cb6d6f)
